export const fakeData = {
  accordion: [
    {
      id: '1',
      title: 'Home',
      icon: 'home',
      hasChildren: false,
      children: [],
    },
    {
      id: '2',
      title: 'Account',
      icon: 'user',
      hasChildren: true,
      children: [
        {
          id: '1',
          title: 'Profile',
          hasChildren: false,
          children: [],
        },
        {
          id: '2',
          title: 'My Orders',
          hasChildren: false,
          children: [],
        },
        {
          id: '3',
          title: 'My Profile',
          hasChildren: false,
          children: [],
        },
        {
          id: '4',
          title: 'Addresses',
          hasChildren: false,
          children: [],
        },
        {
          id: '5',
          title: 'Notification',
          hasChildren: false,
          children: [],
        },
      ],
    },
    {
      id: '3',
      title: 'Shop Pages',
      icon: 'shopping-cart',
      hasChildren: true,
      children: [
        {
          id: '1',
          title: 'Shop',
          hasChildren: false,
          children: [],
        },
        {
          id: '2',
          title: 'Cart',
          hasChildren: false,
          children: [],
        },
        {
          id: '3',
          title: 'Wishlist',
          hasChildren: false,
          children: [],
        },
        {
          id: '4',
          title: 'Product Details',
          hasChildren: false,
          children: [],
        },
        {
          id: '5',
          title: 'Checkout',
          hasChildren: false,
          children: [],
        },
        {
          id: '6',
          title: 'Order Tracking',
          hasChildren: false,
          children: [],
        },
      ],
    },
    {
      id: '4',
      title: 'Payment',
      icon: 'credit-card',
      hasChildren: true,
      children: [
        {
          id: '1',
          title: 'Payment Method',
          hasChildren: false,
          children: [],
        },
        {
          id: '2',
          title: 'Payment Error',
          hasChildren: false,
          children: [],
        },
        {
          id: '3',
          title: 'Payment Completed',
          hasChildren: false,
          children: [],
        },
      ],
    },
    {
      id: '5',
      title: 'Category',
      icon: 'grid',
      hasChildren: true,
      children: [
        {
          id: '1',
          title: 'Category Grid',
          hasChildren: false,
          children: [],
        },
        {
          id: '2',
          title: 'Category List',
          hasChildren: false,
          children: [],
        },
      ],
    },
    {
      id: '6',
      title: 'Authentication',
      icon: 'lock',
      hasChildren: true,
      children: [
        {
          id: '1',
          title: 'Log In',
          hasChildren: false,
          children: [],
        },
        {
          id: '2',
          title: 'Sign Up',
          hasChildren: false,
          children: [],
        },
        {
          id: '3',
          title: 'Verification',
          hasChildren: false,
          children: [],
        },
        {
          id: '4',
          title: 'Change Password',
          hasChildren: false,
          children: [],
        },
        {
          id: '5',
          title: 'Splash',
          hasChildren: false,
          children: [],
        },
        {
          id: '6',
          title: 'Splash 2',
          hasChildren: false,
          children: [],
        },
      ],
    },
    {
      id: '7',
      title: 'Customer Reviews',
      icon: 'star',
      hasChildren: true,
      children: [
        {
          id: '1',
          title: 'Ratings & Reviews',
          hasChildren: false,
          children: [],
        },
        {
          id: '2',
          title: 'Write a Review',
          hasChildren: false,
          children: [],
        },
      ],
    },
    {
      id: '8',
      title: 'About Us',
      icon: 'smile',
      hasChildren: false,
    },
    {
      id: '9',
      title: 'Contact Us',
      icon: 'headphones',
      hasChildren: false,
    },
  ],
}
