export const SCREEN = {
  STACK_HOME: 'HomeStack',
  STACK_CATEGORY: 'CategoryStack',
  STACK_CATEGORY_INNER: 'CategoryInner',
  STACK_CATEGORY_INNER_PAGE: 'CategoryInnerPage',
  STACK_CATEGORY_DETAIL: 'CategoryDetail',
  STACK_PRODUCT_INNER: 'ProductInner',
  STACK_PROFILE: 'ProfileStack',
  STACK_CONTACT: 'ContactStack',
  STACK_SIGN_IN: 'SignIn',
  STACK_SIGN_UP: 'SignUp',
  STACK_MAIN_TAB: 'MainTab',
  STACK_SETTINGS: 'Settings',
  STACK_APPLICATION_INFO: 'ApplicationInfo',
  STACK_NOT_FOUND: 'NotFound',
  TAB_HOME: 'Home',
  TAB_CATEGORY: 'Category',
  TAB_PROFILE: 'Profile',
  TAB_CONTACT: 'Contact',
  DRAWER_MENU: 'Menu',
  DRAWER_ROOT: 'Root',
}
