export const SCREEN = {
  STACK_HOME: 'MainTab',
  STACK_CATEGORY: 'CategoryStack',
  STACK_CATEGORY_INNER: 'CategoryInner',
  STACK_CATEGORY_INNER_PAGE: 'CategoryInnerPage',
  STACK_CATEGORY_DETAIL: 'CategoryDetail',
  STACK_CATEGORY_SEARCH: 'SearchStack',
  STACK_PRODUCT_INNER: 'ProductInner',
  STACK_PROFILE: 'ProfileStack',
  STACK_CONTACT: 'ContactStack',
  STACK_SIGN_IN: 'SignIn',
  STACK_SIGN_UP: 'SignUp',
  STACK_MAIN_TAB: 'MainTab',
  STACK_MAIN_REGISTER: 'MainRegister',
  STACK_PASSWORD: 'PasswordStack',
  STACK_ACCOUNT: 'AccountStack',
  STACK_CREATE_STORE: 'CreateStore',
  STACK_UPDATE_STORE: 'UpdateStore',
  STACK_SETTINGS: 'Settings',
  STACK_APPLICATION_INFO: 'ApplicationInfo',
  STACK_NOT_FOUND: 'NotFound',
  STACK_VERIFICATION: 'VerifyCode',
  STACK_FORGOT_PASSWORD: 'ForgotPassword',
  STACK_WISHLIST: 'Wishlist',
  STACK_SHOP_CART: 'ShopCart',
  STACK_SHOP_LIST: 'ShopList',
  STACK_ORDER_LIST: 'OrderList',
  STACK_ORDER_INNER: 'OrderDetails',
  STACK_ORDER_SUCCESS: 'OrderSuccess',
  STACK_ORDER_FAIL: 'OrderFail',
  TAB_HOME: 'Home',
  TAB_CATEGORY: 'Category',
  TAB_PROFILE: 'Profile',
  TAB_CONTACT: 'Contact',
  DRAWER_MENU: 'Menu',
  DRAWER_ROOT: 'Root',
  PHONE_REGISTER: 'PhoneRegister',
  PARTNER_SHIP: 'ParthnerShip',
  ADD_PARTNERSHIP: 'AddPrtnerShip',
  CHECKOUT: 'Checkout',
  PROFILE_EDIT: 'ProfileEdit',
  CHANGE_PASSWORD: 'ChangePassword',
}

export const MENUS = {
  HOME: 'Home',
  SHOP_LIST: 'Shop List',
  PROFILE: 'Profile',
  PERSONAL_INFO: 'Personal Info',
  CHANGE_PASSWORD: 'Change Password',
  EDIT_PROFILE: 'Edit Profile',
  ORDER_LIST: 'Order List',
  PARTNERS: 'Partners',
  CONTACT_US: 'Contact Us',
}
